version: '3.9'

services:
  webserv:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: app/
    restart: unless-stopped
    container_name: webserv
    ports:
      - "4242:4242"
      - "2121:2121"
    networks:
      - webserv_net

networks:
  webserv_net:
