version: '3.9'

services:
  webserv:
    build:
      context: app/
    restart: unless-stopped
    container_name: webserv
    ports:
      - "4242:4242"
      - "2121:2121"
    networks:
      - webserv_net
    volumes:
      - ./app/tools:/app/tools:ro

networks:
  webserv_net:
