FROM gcc:12 as build

WORKDIR /app

COPY srcs/ .

RUN apt-get update && \
    apt-get install -y && \
    apt-get install vim -y && \
    make

FROM ubuntu:latest

#RUN groupadd -r nikita && useradd -r -g nikita nikita
#
#USER nikita

WORKDIR /app

COPY --from=build /app/webserv .

COPY --from=build /app/configs configs

CMD ["./webserv", "configs/1.conf"]

EXPOSE 4242
EXPOSE 2121
